name: form_bloc_web
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter
  # form_bloc: ^0.10.1
  # form_bloc:
  #   path: ../packages/form_bloc
    # path: ../packages/flutter_form_bloc
  flutter_form_bloc: ^0.11.0
  flutter_gradients: ^1.0.0+1
  flutter_syntax_view: ^1.0.0
  flash: ^1.2.0
  url_launcher: ^5.4.2
  flutter_markdown: ^0.3.4
  simple_animations: ^1.3.9
  auto_size_text: ^2.1.0
  flutter_fadein: ^1.1.1
  liquid_progress_indicator: ^0.3.2
  rxdart: ^0.23.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
  - family: JosefinSans    
    fonts:
    - asset: assets/fonts/JosefinSans-Regular.ttf
    - asset: assets/fonts/JosefinSans-Bold.ttf
      weight: 700
  assets:
    - lib/examples/