name: flutter_form_bloc
description: Create Beautiful Forms in Flutter. The easiest way to Prefill, Async Validation, Update Form Fields, and Show Progress, Failures or Navigate by Reacting to the Form State.
version: 0.29.3
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  bloc: ^7.0.0
  flutter_bloc: ^8.0.0
  form_bloc: ^0.29.0
  equatable: ^2.0.3
#  form_bloc: ^0.20.7-alpha.1
  rxdart: ^0.27.3
  flutter_keyboard_visibility: ^5.0.2
  collection: ^1.15.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
