name: form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface. Async Validation, Progress, Failures, Successes, and more.
version: 0.5.2
author: GiancarloCode <GiancarloCode@gmail.com>
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.6
  bloc: ^0.15.0
  rxdart: ^0.22.2
  equatable: ^0.6.1
  quiver: ^2.0.5
  mockito: ^4.1.1
  pedantic: ^1.8.0+1

dev_dependencies:
  test: ^1.6.0
