name: flutter_form_bloc_example
description: flutter_form_bloc example
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_form_bloc: ^0.30.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
