name: flutter_form_bloc_example
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter
  form_bloc: ^0.10.0
  # form_bloc:
  #   path: ../../form_bloc
  flutter_form_bloc:
    path: ../
  shared_preferences: ^0.5.6+1
  liquid_progress_indicator: ^0.3.2
  image_picker: ^0.6.2+3 
  flushbar: ^1.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
